# Generated by Django 4.2.17 on 2025-01-11 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_id_user_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d14b3868-ccfd-4feb-8517-003d9925c67d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
