# Generated by Django 4.2.17 on 2025-01-17 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_updated_at_alter_userprofile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_img',
            new_name='profile_image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3341d580-0132-4196-b756-3259a5c69d3c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
