# This signifies that this is a .yml file
---
name: Build and deploy container app to Azure Web App - Userdatesting

# Trigger
on:
  push:

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: https://bugbustersktproject.azurecr.io/
          username: ${{secrets.AzureAppService_ContainerUsername}}
          password: ${{secrets.AzureAppService_ContainerPassword}}

      - name: Build and push image to Azure Container Registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: bugbustersktproject.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/cicdtest1-web:${{github.sha}}
          file: ./Dockerfile

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: bugbusterktproject
          slot-name: staging
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          images: bugbustersktproject.azurecr.io/${{secrets.AzureAppService_ContainerUsername}}/cicdtest1-web:${{github.sha}}
