# This signifies that this is a .yml file
---
  name: Checks

  # Trigger
  on:
    push:

  jobs:
    build:
      name: Build and Run
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to registry
          uses: docker/login-action@v2
          with:
            registry: https://bugbustersktproject.azurecr.io/
            username: ${{secrets.AzureAppService_ContainerUsername}}
            password: ${{secrets.AzureAppService_ContainerPassword}}

        - name: Build and push image to Azure Container Registry
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: bugbustersktproject.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/cicdtest1-web:${{github.sha}}
            file: ./Dockerfile
